name: test-github-ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: goto-bus-stop/standard-action@v1.0.0
        with:
          annotate: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
